apiVersion: apps/v1
kind: Deployment
metadata:
  name: rehomefrontend-uat-deploy
  namespace: dev
  labels:
    app: rehomefrontend-uat
spec:
  replicas: 3 # number of pods
  selector:
    matchLabels:
      app: rehomefrontend-uat
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rehomefrontend-uat
    spec:
      containers:
        - name: rehomefrontend-uat
          image: acrrehomedev.azurecr.io/rehomefrontend-uat
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            timeoutSeconds: 120
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: environment-variables-ux
