apiVersion: v1
kind: Service
metadata:
  name: rehomefrontend-uat-svc
  namespace: dev
spec:
  selector:
    app: rehomefrontend-uat
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
