apiVersion: v1
kind: Service
metadata:
  name: rehomefrontend-prod-svc
  namespace: prod
spec:
  selector:
    app: rehomefrontend-prod
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
